import mlflow
import mlflow.sklearn
import os
import pandas as pd
import numpy as np
from scipy.stats import ks_2samp
import shap
import matplotlib.pyplot as plt
from dotenv import load_dotenv

load_dotenv()

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", "sqlite:///mlflow.db")
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

def get_consumption_code(model_name, run_id, task_type, feature_names=None):
    """Generates a Python code snippet to consume the trained model."""
    safe_name = model_name.replace(" ", "_").replace("-", "_").replace("__", "_")
    
    # Gerar dicionário de colunas para o DataFrame de exemplo
    if feature_names and len(feature_names) > 0:
        cols_str = ",\n    ".join([f'"{col}": [0.0]' for col in feature_names[:10]]) # Mostra as primeiras 10
        if len(feature_names) > 10:
            cols_str += f",\n    # ... e mais {len(feature_names)-10} colunas"
    else:
        cols_str = "# \"feature_1\": [1.0], \n    # \"feature_2\": [\"valor\"]"

    code = f"""# --- AutoMLOps Code Sample: Consuming {model_name} ---
import mlflow
import pandas as pd
import numpy as np

# 1. Configurar Tracking (se necessário)
mlflow.set_tracking_uri("{MLFLOW_TRACKING_URI}")

# 2. Carregar o modelo do MLflow
# Você também pode usar 'models:/{model_name}/latest' se tiver registrado o modelo
model_uri = "runs:/{run_id}/{safe_name}"
model = mlflow.sklearn.load_model(model_uri)

print(f"Modelo {{model_uri}} carregado com sucesso!")

# 3. Preparar dados de exemplo (Ajuste conforme suas colunas)
# Exemplo baseado no treinamento:
sample_data = pd.DataFrame({{
    {cols_str}
}})

# 4. Fazer predição
try:
    predictions = model.predict(sample_data)
    print("Resultado da Predição:", predictions)
    
    # Se for classificação, você também pode querer as probabilidades:
    if hasattr(model, "predict_proba"):
        probs = model.predict_proba(sample_data)
        print("Probabilidades:", probs)
except Exception as e:
    print("Erro ao predizer (Verifique se os dados de entrada condizem com o treinamento):", e)
    print("DICA: Use o AutoMLDataProcessor para transformar dados brutos antes do predict.")
"""
    return code

import datetime

def generate_model_card(model_name, params, metrics, feature_names=None, task_type="classification", duration=None):
    """
    Gera um Model Card automatizado no formato Markdown.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_name = model_name.replace(" ", "_").replace("-", "_").replace("__", "_")
    
    # Format Params
    params_md = "\n".join([f"- **{k}**: `{v}`" for k, v in params.items()]) if params else "- N/A"
    
    # Format Metrics
    metrics_md = "\n".join([f"- **{k}**: `{v:.4f}`" if isinstance(v, float) else f"- **{k}**: `{v}`" for k, v in metrics.items() if k not in ['confusion_matrix', 'consumption_code']])
    
    # Format Features
    if feature_names:
        feats_list = feature_names[:20]
        feats_str = ", ".join([f"`{f}`" for f in feats_list])
        if len(feature_names) > 20:
             feats_str += f", e mais {len(feature_names) - 20}..."
        features_md = f"O modelo foi treinado com {len(feature_names)} features. Principais features (até 20):\n{feats_str}"
    else:
        features_md = "Nomes de features não fornecidos ou não disponíveis."

    template = f"""# Model Card: {model_name}

> Este documento foi gerado automaticamente pelo **AutoMLOps Studio**.

## 📖 Resumo
- **Nome do Modelo:** `{model_name}`
- **Tipo de Tarefa:** `{task_type}`
- **Data de Geração:** {now}
- **Tempo de Treinamento (Aprox):** `{duration:.2f} segundos` if duration else 'N/A'

---

## ⚙️ Configurações (Hiperparâmetros)
Os hiperparâmetros abaixo foram encontrados como ótimos durante a busca (Optuna):
{params_md}

---

## 📊 Performance (Validação)
As métricas abaixo representam a performance do modelo no conjunto de validação durante o experimento:
{metrics_md}

---

## 🧬 Dados e Features
{features_md}

### Considerações sobre os Dados
Recomenda-se assegurar que os dados enviados para inferência passem pelo mesmo pipeline de transformação (Scaling, Imputation, etc.) utilizado no treinamento via `AutoMLDataProcessor`.

---

## ⚠️ Limitações e Considerações Éticas
Como este modelo foi construído de forma automatizada (AutoML):
1. **Viés Oculto:** O modelo refletirá vieses presentes nos dados de treinamento. É vital auditar os dados historicamente antes de confiar no modelo para decisões críticas.
2. **Data Drift:** Se a distribuição dos dados de entrada em produção divergir significativamente dos dados usados neste treinamento, a performance (relatada acima) não é garantida. Recomenda-se o monitoramento ativo.
3. **Explicabilidade:** Modelos de *Ensemble* avançados ou Redes Neurais podem ser opacos. Consulte as plotagens de Feature Importance (SHAP/Coeficientes) anexadas a este experimento para maior clareza sobre como as decisões são tomadas.

---
*Generated by AutoMLOps Studio - Model Card Builder*
"""
    return template

class MLFlowTracker:
    def __init__(self, experiment_name):
        self.experiment_name = experiment_name
        mlflow.set_experiment(experiment_name)

    def log_experiment(self, params, metrics, model, model_name, artifacts=None, register=True, feature_names=None):
        with mlflow.start_run():
            mlflow.log_params(params)
            try:
                mlflow.log_metrics(metrics)
            except Exception as e:
                print(f"Warning: Failed to log metrics due to {e}")
            
            # Log model
            safe_artifact_path = model_name.replace(" ", "_").replace("-", "_").replace("__", "_")
            mlflow.sklearn.log_model(
                model, 
                safe_artifact_path, 
                registered_model_name=model_name if register else None
            )
            
            # Log artifacts (e.g., plots, dataset samples)
            if artifacts:
                for art_path in artifacts:
                    if os.path.exists(art_path):
                        mlflow.log_artifact(art_path)
            
            run_id = mlflow.active_run().info.run_id
            
            # Gerar e logar amostra de código de consumo
            try:
                task_type = params.get('task_type', 'classification')
                code_sample = get_consumption_code(model_name, run_id, task_type, feature_names=feature_names)
                code_filename = f"consume_{safe_artifact_path}.py"
                with open(code_filename, "w", encoding="utf-8") as f:
                    f.write(code_sample)
                mlflow.log_artifact(code_filename)
                # Opcionalmente remover o arquivo temporário
                if os.path.exists(code_filename):
                    os.remove(code_filename)
            except Exception as e:
                print(f"Warning: Failed to log code sample: {e}")

            return run_id

class DataLake:
    def __init__(self, base_path="./data_lake"):
        self.base_path = base_path
        if not os.path.exists(base_path):
            os.makedirs(base_path)

    def save_dataset(self, df, name):
        """Save dataset with versioning (timestamp based)."""
        import datetime
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        version_dir = os.path.join(self.base_path, name)
        if not os.path.exists(version_dir):
            os.makedirs(version_dir)
        
        file_path = os.path.join(version_dir, f"v_{timestamp}.csv")
        df.to_csv(file_path, index=False)
        return file_path

    def list_datasets(self):
        if not os.path.exists(self.base_path):
            return []
        return os.listdir(self.base_path)

    def list_versions(self, name):
        version_dir = os.path.join(self.base_path, name)
        if not os.path.exists(version_dir):
            return []
        return sorted(os.listdir(version_dir), reverse=True)

    def load_version(self, name, version, **kwargs):
        file_path = os.path.join(self.base_path, name, version)
        return pd.read_csv(file_path, **kwargs)

class DriftDetector:
    @staticmethod
    def detect_drift(reference_data, current_data, threshold=0.05):
        """Detect drift using Kolmogorov-Smirnov test."""
        drifts = {}
        common_cols = set(reference_data.columns) & set(current_data.columns)
        
        for col in common_cols:
            if pd.api.types.is_numeric_dtype(reference_data[col]):
                stat, p_value = ks_2samp(reference_data[col].dropna(), current_data[col].dropna())
                drifts[col] = {
                    'p_value': p_value,
                    'drift_detected': p_value < threshold
                }
        return drifts

class ModelExplainer:
    def __init__(self, model, X_train, task_type="classification"):
        self.model = model
        self.X_train = X_train
        self.task_type = task_type
        
        # Tentar inicializar o Explainer mais adequado
        try:
            # shap.Explainer tenta detectar automaticamente (Tree, Linear, Deep, etc.)
            # Para modelos sklearn complexos (Pipelines, Voting), pode falhar e cair no fallback
            self.explainer = shap.Explainer(model, X_train)
        except Exception:
            # Fallback explícito para KernelExplainer (genérico, mas mais lento)
            # Usamos um sample do X_train para background data se for muito grande
            background = X_train
            if len(X_train) > 100:
                background = shap.utils.sample(X_train, 100)
                
            if task_type == "classification" and hasattr(model, "predict_proba"):
                self.explainer = shap.KernelExplainer(model.predict_proba, background)
            else:
                self.explainer = shap.KernelExplainer(model.predict, background)

    def get_shap_values(self, X):
        try:
            shap_values = self.explainer(X)
        except:
            shap_values = self.explainer.shap_values(X)
        return shap_values

    def plot_importance(self, X_test, plot_type="summary"):
        """
        Gera plot de importância SHAP.
        plot_type: 'summary' (beeswarm/bar) ou 'bar'
        """
        # Calcular SHAP values para o conjunto de teste
        try:
            shap_values = self.explainer(X_test)
        except:
            # Fallback para shap_values legacy
            shap_values = self.explainer.shap_values(X_test)

        # Tratamento para outputs de classificação (lista de arrays ou objeto Explanation com dimensão extra)
        # Se for lista (um array por classe), geralmente pegamos a classe positiva (índice 1) ou a primeira
        final_shap_values = shap_values
        
        if isinstance(shap_values, list):
            # Ex: [shap_values_class0, shap_values_class1]
            # Tentar pegar a classe 1 (positiva) se existir, senão a 0
            idx = 1 if len(shap_values) > 1 else 0
            final_shap_values = shap_values[idx]
        elif hasattr(shap_values, "values") and len(shap_values.values.shape) == 3:
             # Objeto Explanation com (n_samples, n_features, n_classes)
             # Selecionar classe 1
             idx = 1 if shap_values.values.shape[2] > 1 else 0
             final_shap_values = shap_values[..., idx]

        fig = plt.figure()
        if plot_type == "bar":
            shap.summary_plot(final_shap_values, X_test, plot_type="bar", show=False)
        else:
            shap.summary_plot(final_shap_values, X_test, show=False)
        return fig

def get_all_runs():
    """Retorna todos os experimentos (runs) do MLflow."""
    try:
        from mlflow.tracking import MlflowClient
        client = MlflowClient()
        experiments = client.search_experiments()
        all_runs = []
        for exp in experiments:
            runs = mlflow.search_runs(experiment_ids=[exp.experiment_id])
            if not runs.empty:
                runs['experiment_name'] = exp.name
                all_runs.append(runs)
        
        if all_runs:
            return pd.concat(all_runs, ignore_index=True)
        return pd.DataFrame()
    except Exception as e:
        print(f"Erro ao buscar runs: {e}")
        return pd.DataFrame()

def get_model_registry():
    """List all registered models in MLFlow."""
    try:
        experiments = mlflow.search_experiments()
        runs = mlflow.search_runs(experiment_ids=[exp.experiment_id for exp in experiments])
        # Add experiment name to runs
        exp_map = {exp.experiment_id: exp.name for exp in experiments}
        if not runs.empty:
            runs['experiment_name'] = runs['experiment_id'].map(exp_map)
        return runs
    except Exception as e:
        print(f"Error fetching model registry: {e}")
        return pd.DataFrame()

def register_model_from_run(run_id, model_name):
    """Register a model that was previously logged in a run."""
    try:
        model_uri = f"runs:/{run_id}/model"
        mlflow.register_model(model_uri, model_name)
        return True
    except Exception as e:
        print(f"Error registering model: {e}")
        return False

def get_registered_models():
    """List all models in the Model Registry."""
    try:
        from mlflow.tracking import MlflowClient
        client = MlflowClient()
        return client.search_registered_models()
    except Exception as e:
        print(f"Error fetching registered models: {e}")
        return []

def get_model_details(model_name, version=None):
    """Get details of a registered model version."""
    try:
        from mlflow.tracking import MlflowClient
        client = MlflowClient()
        
        if version is None:
            # Get latest version
            versions = client.get_latest_versions(model_name, stages=["Production", "Staging", "None"])
            if not versions:
                return None
            model_version = versions[0]
        else:
            model_version = client.get_model_version(model_name, version)
            
        run = client.get_run(model_version.run_id)
        
        # Extract metadata
        details = {
            "name": model_name,
            "version": model_version.version,
            "run_id": model_version.run_id,
            "params": run.data.params,
            "metrics": run.data.metrics,
            "tags": run.data.tags,
            "creation_timestamp": model_version.creation_timestamp,
            "status": model_version.status,
            "description": model_version.description,
            "source": model_version.source
        }
        
        return details
    except Exception as e:
        print(f"Error fetching model details: {e}")
        return None

def load_registered_model(model_name, version=None):
    """Load a registered model from MLflow."""
    try:
        if version:
            model_uri = f"models:/{model_name}/{version}"
        else:
            model_uri = f"models:/{model_name}/latest"
            
        return mlflow.sklearn.load_model(model_uri)
    except Exception as e:
        print(f"Error loading registered model: {e}")
        return None
