import json
import nbformat as nbf
import os
import uuid
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)

class WhiteboxNotebookGenerator:
    """
    Generates a SageMaker-style Jupyter Notebook that reproduces
    the winning AutoML pipeline (preprocessing + model training).
    """
    
    def __init__(self, config: Dict[str, Any], best_params: Dict[str, Any], feature_names: List[str] = None, dataset_path: str = None):
        self.config = config
        self.best_params = best_params
        self.feature_names = feature_names or []
        self.dataset_path = dataset_path
        self.nb = nbf.v4.new_notebook()
        
    def generate(self, output_path: str = None) -> str:
        """Constructs the notebook and saves it to disk."""
        
        # 1. Header & Intro
        self._add_markdown("# AutoMLOps Candidate Definition Notebook")
        self._add_markdown(
            "This notebook was automatically generated by AutoMLOps-Studio.\n"
            "It allows you to inspect, customize, and execute the winning machine learning pipeline independently."
        )
        
        # Table of Contents
        self._add_markdown(
            "## Table of Contents\n"
            "- [1. Setup & Imports](#1.-Setup-&-Imports)\n"
            "- [2. Data Loading](#2.-Data-Loading)\n"
            "- [3. Data Preprocessing (Feature Engineering)](#2.5.-Data-Preprocessing-(Feature-Engineering))\n"
            "- [4. Model Definition](#3.-Model-Definition)\n"
            "- [5. Training and Evaluation](#4.-Training-and-Evaluation)"
        )
        
        # 2. Experiment Info
        task_type = self.config.get('task', 'Unknown Task')
        target_col = self.config.get('target', 'Unknown Target')
        model_name = self.best_params.get('model_name', 'Unknown Model')
        opt_metric = self.config.get('optimization_metric', 'accuracy')
        
        from src.utils.pillars import get_model_pillars_profile
        pillars = get_model_pillars_profile(model_name, task_type=task_type, params=self.best_params)
        
        self._add_markdown(
            f"**Task Type:** {task_type.capitalize()}\n"
            f"**Target Column:** {target_col}\n"
            f"**Selected Model:** {model_name}\n"
            f"**Optimization Metric:** `{opt_metric.upper()}`"
        )
        
        self._add_markdown(
            f"### 🏛️ The 5 Pillars of ML (Anatomical Profile of the Winning Model)\n"
            f"- **Pillar 1 (Structure):** `{pillars['pillar_1_structure']['interpretability']}` ({pillars['pillar_1_structure']['type']})\n"
            f"- **Pillar 2 (Signal Source):** `{pillars['pillar_2_signal_source']['signal_source']}`\n"
            f"- **Pillar 3 (Criterion / Loss):** `{pillars['pillar_3_criterion_loss']['loss_function']}` — *Assumed Distribution:* `{pillars['pillar_3_criterion_loss']['assumed_distribution']}`\n"
            f"- **Pillar 4 (Regularization):** `{pillars['pillar_4_regularization']['regularization']}`\n"
            f"- **Pillar 5 (Optimizer Engine):** `{pillars['pillar_5_optimizer']['engine']}` (`{pillars['pillar_5_optimizer']['hyperparameter_tuner']}`)\n\n"
            f"**Training Classification Axes:** {pillars['training_axes']['eager_vs_lazy']} | {pillars['training_axes']['parametric_vs_non_parametric']} | {pillars['training_axes']['convexity']}"
        )
        
        self._add_markdown(f"> **Optimization Target:** This pipeline was automatically tuned by AutoMLOps-Studio to optimize the **{opt_metric.upper()}** metric.")
        
        # 3. Imports
        self._add_markdown("### 1. Setup & Imports")
        self._add_code(
            "import pandas as pd\n"
            "import numpy as np\n"
            "import mlflow\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error\n"
            "from sklearn.metrics import classification_report, confusion_matrix\n"
            "from src.core.processor import AutoMLDataProcessor\n\n"
            "# Configure visualization style\n"
            "sns.set_theme(style='whitegrid')\n"
            "plt.rcParams['figure.figsize'] = (10, 6)"
        )
        
        # 4. Data Loading
        self._add_markdown("### 2. Data Loading")
        temporal_tasks = ('time_series', 'forecast', 'forecast_classification', 'ts_clustering')
        shuffle = "False" if (task_type in temporal_tasks or self.config.get('is_time_series')) else "True"
        
        if self.dataset_path:
            self._add_markdown("Loading the exact dataset used during the AutoML session.")
            
            # Format path safely for windows/linux
            safe_path = self.dataset_path.replace('\\', '\\\\')
            
            self._add_code(
                f"df = pd.read_csv('{safe_path}')\n\n"
                f"target_col = '{target_col}'\n"
                f"X = df.drop(columns=[target_col])\n"
                f"y = df[target_col]\n"
                f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle={shuffle})"
            )
        else:
            self._add_markdown("Load your original dataset here. The code below assumes you have loaded it into a pandas DataFrame named `df`.")
            self._add_code(
                "# Replace with your actual dataset path\n"
                "# df = pd.read_csv('your_dataset.csv')\n\n"
                f"target_col = '{target_col}'\n"
                "# X = df.drop(columns=[target_col])\n"
                "# y = df[target_col]\n"
                f"# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle={shuffle})"
            )
        
        # 4.5. Data Preprocessing
        self._add_markdown("### 2.5. Data Preprocessing (Feature Engineering)")
        self._add_markdown(
            "Instantiating the exact data processor used during the AutoML session.\n"
            "This step handles missing values, categorical encoding, NLP embeddings, and Deep Feature Synthesis (DFS)."
        )
        self._add_code(
            f"processor = AutoMLDataProcessor(target_column='{target_col}', task_type='{task_type}')\n\n"
            "# Fit the processor on training data and transform it\n"
            "X_train_proc, y_train_proc = processor.fit_transform(X_train, y_train)\n\n"
            "# Transform the test data using the fitted processor\n"
            "X_test_proc, y_test_proc = processor.transform(X_test, y_test)"
        )
        
        # 5. Model Definition
        self._add_markdown("### 3. Model Definition")
        self._add_markdown(
            f"Instantiating the winning **{model_name}** model with the optimal hyperparameters found during the AutoML search."
        )
        
        model_code = self._get_model_instantiation_code()
        self._add_code(model_code)
        
        # 6. Training & Evaluation
        self._add_markdown("### 4. Training and Evaluation")
        self._add_markdown("This section trains the model and generates a comprehensive performance report, including visual diagnostics.")
        
        metric_map = {
            'accuracy': ('accuracy_score', ''),
            'f1': ('f1_score', ", average='macro'"),
            'precision': ('precision_score', ", average='macro'"),
            'recall': ('recall_score', ", average='macro'"),
            'roc_auc': ('roc_auc_score', ''),
            'r2': ('r2_score', ''),
            'rmse': ('mean_squared_error', ", squared=False"),
            'mae': ('mean_absolute_error', ''),
            'mape': ('mean_absolute_percentage_error', '')
        }
        metric_fn, metric_kwargs = metric_map.get(opt_metric, ('accuracy_score' if task_type in ('classification', 'forecast_classification') else 'mean_squared_error', ''))
        
        is_classification = task_type in ('classification', 'forecast_classification')
        
        eval_code = ""
        if is_classification:
            eval_code = (
                "    # Detailed Classification Report\n"
                "    print('\\n--- Classification Report ---')\n"
                "    print(classification_report(y_test_proc, preds))\n\n"
                "    # Confusion Matrix Plot\n"
                "    fig_cm, ax_cm = plt.subplots(figsize=(8, 6))\n"
                "    cm = confusion_matrix(y_test_proc, preds)\n"
                "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax_cm)\n"
                "    ax_cm.set_title('Confusion Matrix')\n"
                "    ax_cm.set_ylabel('Actual')\n"
                "    ax_cm.set_xlabel('Predicted')\n"
                "    plt.tight_layout()\n"
                "    plt.show()\n"
                "    mlflow.log_figure(fig_cm, 'confusion_matrix.png')\n"
            )
        else:
            eval_code = (
                "    # Detailed Regression Metrics\n"
                "    print('\\n--- Regression Report ---')\n"
                "    print(f'RMSE: {mean_squared_error(y_test_proc, preds, squared=False):.4f}')\n"
                "    print(f'MAE:  {mean_absolute_error(y_test_proc, preds):.4f}')\n"
                "    print(f'R2:   {r2_score(y_test_proc, preds):.4f}')\n\n"
                "    # Actual vs Predicted Plot\n"
                "    fig_scatter, ax_scatter = plt.subplots(figsize=(8, 6))\n"
                "    ax_scatter.scatter(y_test_proc, preds, alpha=0.5, color='blue')\n"
                "    ax_scatter.plot([y_test_proc.min(), y_test_proc.max()], [y_test_proc.min(), y_test_proc.max()], 'r--', lw=2)\n"
                "    ax_scatter.set_title('Actual vs Predicted')\n"
                "    ax_scatter.set_xlabel('Actual Values')\n"
                "    ax_scatter.set_ylabel('Predicted Values')\n"
                "    plt.tight_layout()\n"
                "    plt.show()\n"
                "    mlflow.log_figure(fig_scatter, 'actual_vs_predicted.png')\n\n"
                "    # Residuals Plot\n"
                "    fig_res, ax_res = plt.subplots(figsize=(8, 6))\n"
                "    residuals = y_test_proc - preds\n"
                "    sns.histplot(residuals, kde=True, ax=ax_res, color='purple')\n"
                "    ax_res.set_title('Residuals Distribution')\n"
                "    plt.tight_layout()\n"
                "    plt.show()\n"
                "    mlflow.log_figure(fig_res, 'residuals_distribution.png')\n"
            )

        feat_imp_code = (
            "    # Feature Importance Plot (if supported by model)\n"
            "    if hasattr(model, 'feature_importances_'):\n"
            "        try:\n"
            "            importances = model.feature_importances_\n"
            "            # Try to get feature names\n"
            "            feat_names = processor.get_feature_names() if hasattr(processor, 'get_feature_names') else [f'Feature {i}' for i in range(len(importances))]\n"
            "            if len(feat_names) != len(importances):\n"
            "                feat_names = [f'Feature {i}' for i in range(len(importances))]\n"
            "            \n"
            "            imp_df = pd.DataFrame({'Feature': feat_names, 'Importance': importances})\n"
            "            imp_df = imp_df.sort_values(by='Importance', ascending=False).head(15)\n\n"
            "            fig_fi, ax_fi = plt.subplots(figsize=(10, 8))\n"
            "            sns.barplot(x='Importance', y='Feature', data=imp_df, ax=ax_fi, palette='viridis')\n"
            "            ax_fi.set_title('Top 15 Feature Importances')\n"
            "            plt.tight_layout()\n"
            "            plt.show()\n"
            "            mlflow.log_figure(fig_fi, 'feature_importance.png')\n"
            "        except Exception as e:\n"
            "            print(f'Could not plot feature importance: {e}')\n"
        )

        if self.dataset_path:
            self._add_code(
                "mlflow.set_experiment('Whitebox_Notebook_Runs')\n"
                "with mlflow.start_run(run_name='Manual_Execution'):\n"
                f"    mlflow.log_param('model', '{model_name}')\n"
                "    # Train the model\n"
                "    model.fit(X_train_proc, y_train_proc)\n\n"
                "    # Predict and Evaluate\n"
                "    preds = model.predict(X_test_proc)\n"
                f"    score = {metric_fn}(y_test_proc, preds{metric_kwargs})\n"
                f"    print('Optimization Target ({opt_metric.upper()}):', score)\n"
                f"    mlflow.log_metric('{opt_metric}', score)\n\n"
                f"{eval_code}\n"
                f"{feat_imp_code}\n"
                "    # Save Model\n"
                "    try:\n"
                "        mlflow.sklearn.log_model(model, 'model')\n"
                "    except Exception:\n"
                "        pass # For PyTorch models, custom logging might be required"
            )
        else:
            self._add_code(
                "# mlflow.set_experiment('Whitebox_Notebook_Runs')\n"
                "# with mlflow.start_run(run_name='Manual_Execution'):\n"
                f"#     mlflow.log_param('model', '{model_name}')\n"
                "#     # Train the model\n"
                "#     model.fit(X_train_proc, y_train_proc)\n\n"
                "#     # Predict and Evaluate\n"
                "#     preds = model.predict(X_test_proc)\n"
                f"#     score = {metric_fn}(y_test_proc, preds{metric_kwargs})\n"
                f"#     print('Optimization Target ({opt_metric.upper()}):', score)\n"
                f"#     mlflow.log_metric('{opt_metric}', score)\n\n"
                "#     # ---------------------------------------------------------\n"
                "#     # NOTE: Uncomment the evaluation logic below when running!\n"
                "#     # ---------------------------------------------------------\n"
                f"# {eval_code.replace('    ', '#     ')}\n"
                f"# {feat_imp_code.replace('    ', '#     ')}\n"
                "#     # Save Model\n"
                "#     try:\n"
                "#         mlflow.sklearn.log_model(model, 'model')\n"
                "#     except Exception:\n"
                "#         pass"
            )
        
        # Save to disk
        if not output_path:
            filename = f"automl_candidate_pipeline_{uuid.uuid4().hex[:6]}.ipynb"
            output_path = os.path.join(os.getcwd(), filename)
            
        with open(output_path, 'w', encoding='utf-8') as f:
            nbf.write(self.nb, f)
            
        logger.info(f"Whitebox Notebook generated at: {output_path}")
        return output_path

    def _add_markdown(self, text: str):
        self.nb.cells.append(nbf.v4.new_markdown_cell(text))
        
    def _add_code(self, code: str):
        self.nb.cells.append(nbf.v4.new_code_cell(code))
        
    def _get_model_instantiation_code(self) -> str:
        """Converts best_params into a python code string that instantiates the model."""
        model_name = self.best_params.get('model_name', '')
        params = {k: v for k, v in self.best_params.items() if k != 'model_name'}
        
        # Format params dict into kwargs string
        kwargs_str = ", ".join([f"{k}={repr(v)}" for k, v in params.items()])
        
        if "XGB" in model_name:
            import_str = "from xgboost import XGBClassifier, XGBRegressor"
            model_class = "XGBClassifier" if self.config.get('task') in ('classification', 'forecast_classification') else "XGBRegressor"
        elif "LGBM" in model_name:
            import_str = "from lightgbm import LGBMClassifier, LGBMRegressor"
            model_class = "LGBMClassifier" if self.config.get('task') in ('classification', 'forecast_classification') else "LGBMRegressor"
        elif "CatBoost" in model_name:
            import_str = "from catboost import CatBoostClassifier, CatBoostRegressor"
            model_class = "CatBoostClassifier" if self.config.get('task') in ('classification', 'forecast_classification') else "CatBoostRegressor"
        elif "RandomForest" in model_name:
            import_str = "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor"
            model_class = "RandomForestClassifier" if self.config.get('task') in ('classification', 'forecast_classification') else "RandomForestRegressor"
        elif "LogisticRegression" in model_name or "Ridge" in model_name or "Lasso" in model_name:
            import_str = "from sklearn.linear_model import LogisticRegression, Ridge, Lasso"
            model_class = model_name
        elif "LSTM" in model_name or "TCN" in model_name:
            import_str = "from src.engines.pytorch_forecast import PyTorchLSTMRegressor, PyTorchTCNRegressor"
            model_class = model_name
        elif "LDA" in model_name or "LinearDiscriminantAnalysis" in model_name:
            import_str = "from sklearn.discriminant_analysis import LinearDiscriminantAnalysis"
            model_class = "LinearDiscriminantAnalysis"
        elif "NCA" in model_name or "NeighborhoodComponentsAnalysis" in model_name:
            import_str = "from sklearn.neighbors import NeighborhoodComponentsAnalysis"
            model_class = "NeighborhoodComponentsAnalysis"
        elif "PLS" in model_name or "PLSRegression" in model_name:
            import_str = "from sklearn.cross_decomposition import PLSRegression"
            model_class = "PLSRegression"
        elif "PCA" in model_name:
            import_str = "from sklearn.decomposition import PCA"
            model_class = "PCA"
        elif "SVD" in model_name or "TruncatedSVD" in model_name:
            import_str = "from sklearn.decomposition import TruncatedSVD"
            model_class = "TruncatedSVD"
        else:
            import_str = "# Import your custom model here"
            model_class = model_name or "YourModelClass"

        code = f"{import_str}\n\nmodel = {model_class}({kwargs_str})\nprint(model)"
        return code
